import turtle

def outline():
    outline = turtle.Turtle()
    outline.penup()
    outline.hideturtle()
    outline.setposition(100, 250)
    outline.pendown()
    outline.pensize(5)
    outline.color("blue")
    
    for side in range (8):
        outline.right(45)
        outline.forward(200)

def logoC():
    verge1 = turtle.Turtle()
    verge2 = turtle.Turtle()
    verge3 = turtle.Turtle()
    verge4 = turtle.Turtle()
    verge5 = turtle.Turtle()
    verge6 = turtle.Turtle()
    verge1.pencolor("blue")
    verge2.pencolor("blue")
    verge3.pencolor("blue")
    verge4.pencolor("blue")
    verge5.pencolor("blue")
    verge6.pencolor("blue")

    #Ordered Controls
    verge1.penup()
    verge1.hideturtle()
    verge1.setposition(-240, 110)
    verge1.pendown()
    verge1.pensize(5)
    verge2.penup()
    verge2.hideturtle()
    verge2.setposition(-240, 85)
    verge2.pendown()
    verge2.pensize(5)
    verge3.penup()
    verge3.hideturtle()
    verge3.setposition(-240, 45)
    verge3.pendown()
    verge3.pensize(5)
    verge4.penup()
    verge4.hideturtle()
    verge4.setposition(-240, -25)
    verge4.pendown()
    verge4.pensize(5)
    verge5.penup()
    verge5.hideturtle()
    verge5.setposition(-240, -65)
    verge5.pendown()
    verge5.pensize(5)
    verge6.penup()
    verge6.hideturtle()
    verge6.setposition(-240, -90)
    verge6.pendown()
    verge6.pensize(5)
    verge3.forward(20)
    verge3.right(45)
    verge3.forward(30)
    verge3.left(45)
    verge3.forward(60)
    verge4.forward(20)
    verge4.left(45)
    verge4.forward(30)
    verge4.right(45)
    verge4.forward(60)
    verge5.forward(100)
    verge2.forward(100)
    verge1.forward(35)
    verge1.right(45)
    verge1.forward(35)
    verge6.forward(35)
    verge6.left(45)
    verge6.forward(35)
    verge3.right(90)
    verge3.forward(90)
    verge4.left(90)
    verge4.forward(90)
    verge5.right(45)
    verge5.forward(75)
    verge5.left(45)
    verge5.forward(75)
    verge5.pensize(0.5)
    verge5.showturtle()
    verge5.shapesize(0.5)
    verge5.shape("circle")
    verge2.left(45)
    verge2.forward(75)
    verge2.right(45)
    verge2.forward(75)
    verge2.pensize(0.5)
    verge2.showturtle()
    verge2.shapesize(0.5)
    verge2.shape("circle")

def logoP():
    topVerge1 = turtle.Turtle()
    topVerge2 = turtle.Turtle()
    sideVerge1 = turtle.Turtle()
    sideVerge2 = turtle.Turtle()
    topVerge1.pencolor("blue")
    topVerge2.pencolor("blue")
    sideVerge1.pencolor("blue")
    sideVerge2.pencolor("blue")

    #ordered controls
    topVerge1.penup()
    topVerge1.hideturtle()
    topVerge1.setposition(-10, 250)
    topVerge1.pendown()
    topVerge1.pensize(5)
    topVerge2.penup()
    topVerge2.hideturtle()
    topVerge2.setposition(15, 250)
    topVerge2.pendown()
    topVerge2.pensize(5)
    sideVerge1.penup()
    sideVerge1.hideturtle()
    sideVerge1.setposition(240, 110)
    sideVerge1.right(180)
    sideVerge1.pendown()
    sideVerge1.pensize(5)
    sideVerge2.penup()
    sideVerge2.hideturtle()
    sideVerge2.setposition(240, 30)
    sideVerge2.right(180)
    sideVerge2.pendown()
    sideVerge2.pensize(5)
    topVerge1.right(90)
    topVerge1.forward(75)
    topVerge1.left(45)
    topVerge1.forward(35)
    topVerge2.right(90)
    topVerge2.forward(368)
    topVerge2.shape("circle")
    topVerge2.showturtle()
    topVerge2.shapesize(0.5)
    sideVerge1.forward(30)
    sideVerge1.left(45)
    sideVerge1.forward(30)
    sideVerge1.right(45)
    sideVerge1.forward(55)
    sideVerge2.forward(30)
    sideVerge2.right(45)
    sideVerge2.forward(30)
    sideVerge2.left(45)
    sideVerge2.forward(55)
    sideVerge2.right(90)
    sideVerge2.forward(60)
    sideVerge2.left(45)
    sideVerge2.forward(35)
    sideVerge2.left(45)
    sideVerge2.forward(95)
    sideVerge1.left(90)
    sideVerge1.forward(60)
    sideVerge1.right(45)
    sideVerge1.forward(35)
    sideVerge1.right(45)
    sideVerge1.forward(95)

def outcast():
    outcastVerge1 = turtle.Turtle()
    outcastVerge2 = turtle.Turtle()
    outcastVerge1.pencolor("black")
    outcastVerge2.pencolor("black")

    #ordered controls
    outcastVerge1.penup()
    outcastVerge1.hideturtle()
    outcastVerge1.setposition(200, -130)
    outcastVerge1.right(180)
    outcastVerge1.pendown()
    outcastVerge1.pensize(2)
    outcastVerge2.penup()
    outcastVerge2.hideturtle()
    outcastVerge2.setposition(130, -200)
    outcastVerge2.right(180)
    outcastVerge2.pendown()
    outcastVerge2.pensize(2)
    outcastVerge1.right(45)
    outcastVerge1.forward(75)
    outcastVerge1.left(45)
    outcastVerge1.forward(70)
    outcastVerge2.right(45)
    outcastVerge2.forward(75)
    outcastVerge2.right(45)
    outcastVerge2.forward(70)
    outcastVerge2.left(45)
    outcastVerge2.forward(50)
    outcastVerge2.shapesize(0.5)
    outcastVerge2.shape("circle")
    outcastVerge2.showturtle()

def main():
    outline()
    logoC()
    logoP()
    outcast()
main()
